// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/data.proto

package data

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionerInfo struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Private              []byte   `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionerInfo) Reset()         { *m = ActionerInfo{} }
func (m *ActionerInfo) String() string { return proto.CompactTextString(m) }
func (*ActionerInfo) ProtoMessage()    {}
func (*ActionerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8d492558f417f, []int{0}
}

func (m *ActionerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionerInfo.Unmarshal(m, b)
}
func (m *ActionerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionerInfo.Marshal(b, m, deterministic)
}
func (m *ActionerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionerInfo.Merge(m, src)
}
func (m *ActionerInfo) XXX_Size() int {
	return xxx_messageInfo_ActionerInfo.Size(m)
}
func (m *ActionerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ActionerInfo proto.InternalMessageInfo

func (m *ActionerInfo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ActionerInfo) GetPrivate() []byte {
	if m != nil {
		return m.Private
	}
	return nil
}

type ServiceInfo struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  string        `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Private              []byte        `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	Actioner             *ActionerInfo `protobuf:"bytes,4,opt,name=actioner,proto3" json:"actioner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8d492558f417f, []int{1}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ServiceInfo) GetPrivate() []byte {
	if m != nil {
		return m.Private
	}
	return nil
}

func (m *ServiceInfo) GetActioner() *ActionerInfo {
	if m != nil {
		return m.Actioner
	}
	return nil
}

type PipelineConfig struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directed             bool           `protobuf:"varint,2,opt,name=directed,proto3" json:"directed,omitempty"`
	Services             []*ServiceInfo `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PipelineConfig) Reset()         { *m = PipelineConfig{} }
func (m *PipelineConfig) String() string { return proto.CompactTextString(m) }
func (*PipelineConfig) ProtoMessage()    {}
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8d492558f417f, []int{2}
}

func (m *PipelineConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineConfig.Unmarshal(m, b)
}
func (m *PipelineConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineConfig.Marshal(b, m, deterministic)
}
func (m *PipelineConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineConfig.Merge(m, src)
}
func (m *PipelineConfig) XXX_Size() int {
	return xxx_messageInfo_PipelineConfig.Size(m)
}
func (m *PipelineConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineConfig proto.InternalMessageInfo

func (m *PipelineConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipelineConfig) GetDirected() bool {
	if m != nil {
		return m.Directed
	}
	return false
}

func (m *PipelineConfig) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type RoamingConfig struct {
	Pipeline             *PipelineConfig `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoamingConfig) Reset()         { *m = RoamingConfig{} }
func (m *RoamingConfig) String() string { return proto.CompactTextString(m) }
func (*RoamingConfig) ProtoMessage()    {}
func (*RoamingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e8d492558f417f, []int{3}
}

func (m *RoamingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoamingConfig.Unmarshal(m, b)
}
func (m *RoamingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoamingConfig.Marshal(b, m, deterministic)
}
func (m *RoamingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoamingConfig.Merge(m, src)
}
func (m *RoamingConfig) XXX_Size() int {
	return xxx_messageInfo_RoamingConfig.Size(m)
}
func (m *RoamingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RoamingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RoamingConfig proto.InternalMessageInfo

func (m *RoamingConfig) GetPipeline() *PipelineConfig {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionerInfo)(nil), "data.ActionerInfo")
	proto.RegisterType((*ServiceInfo)(nil), "data.ServiceInfo")
	proto.RegisterType((*PipelineConfig)(nil), "data.PipelineConfig")
	proto.RegisterType((*RoamingConfig)(nil), "data.RoamingConfig")
}

func init() {
	proto.RegisterFile("data/data.proto", fileDescriptor_48e8d492558f417f)
}

var fileDescriptor_48e8d492558f417f = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0x53, 0x51, 0x73, 0x29, 0xff, 0x0c, 0x43, 0xd4, 0x29, 0xca, 0x94, 0x85, 0x04,
	0x05, 0xc4, 0xc0, 0x56, 0x18, 0x80, 0xad, 0x72, 0x37, 0x36, 0x27, 0xb9, 0x16, 0x4b, 0xad, 0x1d,
	0xb9, 0x4e, 0x51, 0x07, 0xbe, 0x3b, 0x8a, 0x93, 0x46, 0x8d, 0x94, 0xc5, 0xba, 0xb3, 0xee, 0xbd,
	0xf7, 0x3b, 0x1d, 0x5c, 0x17, 0xdc, 0xf0, 0xa4, 0x7e, 0xe2, 0x52, 0x2b, 0xa3, 0xe8, 0xb8, 0xae,
	0xc3, 0x57, 0x98, 0xce, 0x73, 0x23, 0x94, 0x44, 0xfd, 0x25, 0x57, 0x8a, 0xde, 0x80, 0x5b, 0x69,
	0xe1, 0x3b, 0x81, 0x13, 0x5d, 0xb0, 0xba, 0xa4, 0x3e, 0x4c, 0x4a, 0x2d, 0xf6, 0xdc, 0xa0, 0x3f,
	0x0a, 0x9c, 0x68, 0xca, 0x8e, 0x6d, 0xf8, 0x07, 0xde, 0x12, 0xf5, 0x5e, 0xe4, 0x68, 0xa5, 0x14,
	0xc6, 0x92, 0x6f, 0xb1, 0xd5, 0xda, 0xfa, 0x68, 0x37, 0x1a, 0xb4, 0x73, 0x7b, 0x76, 0x34, 0x06,
	0xc2, 0x5b, 0x14, 0x7f, 0x1c, 0x38, 0x91, 0x97, 0xd2, 0xd8, 0xf2, 0x9e, 0x02, 0xb2, 0x6e, 0x26,
	0x54, 0x70, 0xb5, 0x10, 0x25, 0x6e, 0x84, 0xc4, 0x77, 0x25, 0x57, 0x62, 0x3d, 0x48, 0x30, 0x03,
	0x52, 0x08, 0x8d, 0xb9, 0xc1, 0xc2, 0x62, 0x10, 0xd6, 0xf5, 0xf4, 0x01, 0xc8, 0xae, 0x59, 0x60,
	0xe7, 0xbb, 0x81, 0x1b, 0x79, 0xe9, 0x6d, 0x93, 0x78, 0xb2, 0x16, 0xeb, 0x46, 0xc2, 0x39, 0x5c,
	0x32, 0xc5, 0xb7, 0x42, 0xae, 0xdb, 0xbc, 0x47, 0x20, 0x65, 0x4b, 0x60, 0x33, 0xbd, 0xf4, 0xbe,
	0xd1, 0xf7, 0xb9, 0x58, 0x37, 0x95, 0xce, 0x61, 0xf2, 0xa1, 0x11, 0x0d, 0x6a, 0xfa, 0x02, 0x64,
	0xc9, 0x0f, 0x9f, 0xb8, 0xd9, 0x28, 0x7a, 0xd7, 0xc8, 0x7a, 0xee, 0xb3, 0xa1, 0xcf, 0xf0, 0xec,
	0xed, 0xf9, 0x3b, 0x5d, 0x0b, 0xf3, 0x53, 0x65, 0x71, 0xae, 0xb6, 0xc9, 0x2f, 0x66, 0x19, 0xea,
	0x64, 0x2f, 0x4a, 0xd4, 0x4b, 0x53, 0x15, 0x87, 0xe4, 0x98, 0xb5, 0xa8, 0xaf, 0x9c, 0x55, 0x2b,
	0x7b, 0xf3, 0xec, 0xdc, 0x1e, 0xfd, 0xe9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x09, 0x01, 0x4f, 0xab,
	0x07, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *RoamingConfig, opts ...grpc.CallOption) (*RoamingConfig, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *RoamingConfig, opts ...grpc.CallOption) (*RoamingConfig, error) {
	out := new(RoamingConfig)
	err := c.cc.Invoke(ctx, "/data.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *RoamingConfig) (*RoamingConfig, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *RoamingConfig) (*RoamingConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoamingConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*RoamingConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/data.proto",
}
