Server:
  id: 1
  tcpbind: 172.11.22.33:6699
  dashboardbind: 172.11.22.33:6006
  maxsize : 10m
  private:
    players:
      - name: Lebrone
        number: 23
        team:
          - Cavs
          - Heat
          - Lakers
      - name: James
        number: 23
        team:
          - OKC
          - HOU
          - NET
    country: USA
    sizes:
      - 10
      - 20
      - 30