Server:
  id: 1
  tcpbind: 172.11.22.33:6699
  dashboardbind: 172.11.22.33:6006
  maxsize : 10m
  private:
    james:
      name: Lebrone James
      team: Los Angeles Lakers
      number: 23
    curry:
      name: Stephen Curry
      team: Golen State Warriors
      number: 9
    country: USA
    sizes:
      - 10
      - 20
      - 30