connects:
  roster:
    initiator:
      kind: remote-grpc
      name: Roster-Initiator
      target: 0.0.0.0:50053
  profile:
    initiator:
      kind: remote-grpc
      name: Profile-Initiator
      target: 0.0.0.0:50051
    trigger:
      kind: remote-grpc
      name: Profile-Trigger
      target: 0.0.0.0:50054
  tail:
    initiator:
      kind: remote-grpc
      name: Tail-Initiator
      target: 0.0.0.0:50052