// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionerInfo struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Private              []byte   `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionerInfo) Reset()         { *m = ActionerInfo{} }
func (m *ActionerInfo) String() string { return proto.CompactTextString(m) }
func (*ActionerInfo) ProtoMessage()    {}
func (*ActionerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *ActionerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionerInfo.Unmarshal(m, b)
}
func (m *ActionerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionerInfo.Marshal(b, m, deterministic)
}
func (m *ActionerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionerInfo.Merge(m, src)
}
func (m *ActionerInfo) XXX_Size() int {
	return xxx_messageInfo_ActionerInfo.Size(m)
}
func (m *ActionerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ActionerInfo proto.InternalMessageInfo

func (m *ActionerInfo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ActionerInfo) GetPrivate() []byte {
	if m != nil {
		return m.Private
	}
	return nil
}

type ServiceInfo struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri                  string        `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Private              []byte        `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	Actioner             *ActionerInfo `protobuf:"bytes,4,opt,name=actioner,proto3" json:"actioner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ServiceInfo) GetPrivate() []byte {
	if m != nil {
		return m.Private
	}
	return nil
}

func (m *ServiceInfo) GetActioner() *ActionerInfo {
	if m != nil {
		return m.Actioner
	}
	return nil
}

type PipelineConfig struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directed             bool           `protobuf:"varint,2,opt,name=directed,proto3" json:"directed,omitempty"`
	Services             []*ServiceInfo `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PipelineConfig) Reset()         { *m = PipelineConfig{} }
func (m *PipelineConfig) String() string { return proto.CompactTextString(m) }
func (*PipelineConfig) ProtoMessage()    {}
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *PipelineConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineConfig.Unmarshal(m, b)
}
func (m *PipelineConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineConfig.Marshal(b, m, deterministic)
}
func (m *PipelineConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineConfig.Merge(m, src)
}
func (m *PipelineConfig) XXX_Size() int {
	return xxx_messageInfo_PipelineConfig.Size(m)
}
func (m *PipelineConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineConfig proto.InternalMessageInfo

func (m *PipelineConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipelineConfig) GetDirected() bool {
	if m != nil {
		return m.Directed
	}
	return false
}

func (m *PipelineConfig) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type RoamingConfig struct {
	Pipeline             *PipelineConfig `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoamingConfig) Reset()         { *m = RoamingConfig{} }
func (m *RoamingConfig) String() string { return proto.CompactTextString(m) }
func (*RoamingConfig) ProtoMessage()    {}
func (*RoamingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *RoamingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoamingConfig.Unmarshal(m, b)
}
func (m *RoamingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoamingConfig.Marshal(b, m, deterministic)
}
func (m *RoamingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoamingConfig.Merge(m, src)
}
func (m *RoamingConfig) XXX_Size() int {
	return xxx_messageInfo_RoamingConfig.Size(m)
}
func (m *RoamingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RoamingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RoamingConfig proto.InternalMessageInfo

func (m *RoamingConfig) GetPipeline() *PipelineConfig {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionerInfo)(nil), "main.ActionerInfo")
	proto.RegisterType((*ServiceInfo)(nil), "main.ServiceInfo")
	proto.RegisterType((*PipelineConfig)(nil), "main.PipelineConfig")
	proto.RegisterType((*RoamingConfig)(nil), "main.RoamingConfig")
}

func init() {
	proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd)
}

var fileDescriptor_871986018790d2fd = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x95, 0x26, 0x02, 0x73, 0x29, 0x08, 0x2c, 0x06, 0x8b, 0x29, 0xca, 0x94, 0x05, 0x0b,
	0x85, 0x8d, 0xad, 0x62, 0x62, 0x43, 0xe6, 0x09, 0x4c, 0x72, 0xad, 0x4e, 0x22, 0xb6, 0xe5, 0x9a,
	0x6e, 0xbc, 0x3b, 0xaa, 0xe3, 0x5a, 0xad, 0x94, 0xed, 0x4e, 0xfa, 0x7f, 0xfc, 0xee, 0x00, 0x46,
	0x1d, 0xb4, 0x74, 0xde, 0x06, 0xcb, 0xab, 0x49, 0x93, 0x69, 0xdf, 0x60, 0xbd, 0x19, 0x02, 0x59,
	0x83, 0xfe, 0xc3, 0x6c, 0x2d, 0xbf, 0x87, 0xf2, 0xd7, 0x93, 0x28, 0x9a, 0xa2, 0xbb, 0x51, 0xc7,
	0x91, 0x0b, 0xb8, 0x76, 0x9e, 0x0e, 0x3a, 0xa0, 0x58, 0x35, 0x45, 0xb7, 0x56, 0xa7, 0xb5, 0xfd,
	0x83, 0xfa, 0x0b, 0xfd, 0x81, 0x06, 0x8c, 0x56, 0x0e, 0x95, 0xd1, 0x13, 0x26, 0x6f, 0x9c, 0x4f,
	0x71, 0xab, 0xc5, 0xb8, 0xf2, 0x22, 0x8e, 0x4b, 0x60, 0x3a, 0xa1, 0x88, 0xaa, 0x29, 0xba, 0xba,
	0xe7, 0xf2, 0xc8, 0x28, 0xcf, 0x01, 0x55, 0xd6, 0xb4, 0x16, 0xee, 0x3e, 0xc9, 0xe1, 0x0f, 0x19,
	0x7c, 0xb7, 0x66, 0x4b, 0xbb, 0x45, 0x82, 0x27, 0x60, 0x23, 0x79, 0x1c, 0x02, 0x8e, 0x11, 0x83,
	0xa9, 0xbc, 0xf3, 0x67, 0x60, 0xfb, 0xf9, 0x80, 0xbd, 0x28, 0x9b, 0xb2, 0xab, 0xfb, 0x87, 0xb9,
	0xf1, 0xec, 0x2c, 0x95, 0x25, 0xed, 0x06, 0x6e, 0x95, 0xd5, 0x13, 0x99, 0x5d, 0xea, 0x7b, 0x01,
	0xe6, 0x12, 0x41, 0xec, 0xac, 0xfb, 0xc7, 0xd9, 0x7f, 0xc9, 0xa5, 0xb2, 0xea, 0xfb, 0x2a, 0xfe,
	0xfe, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x13, 0x04, 0x34, 0x89, 0x01, 0x00, 0x00,
}
