// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitiatorConfig struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiatorConfig) Reset()         { *m = InitiatorConfig{} }
func (m *InitiatorConfig) String() string { return proto.CompactTextString(m) }
func (*InitiatorConfig) ProtoMessage()    {}
func (*InitiatorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *InitiatorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatorConfig.Unmarshal(m, b)
}
func (m *InitiatorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatorConfig.Marshal(b, m, deterministic)
}
func (m *InitiatorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatorConfig.Merge(m, src)
}
func (m *InitiatorConfig) XXX_Size() int {
	return xxx_messageInfo_InitiatorConfig.Size(m)
}
func (m *InitiatorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatorConfig proto.InternalMessageInfo

func (m *InitiatorConfig) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *InitiatorConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitiatorConfig) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type TriggerConfig struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerConfig) Reset()         { *m = TriggerConfig{} }
func (m *TriggerConfig) String() string { return proto.CompactTextString(m) }
func (*TriggerConfig) ProtoMessage()    {}
func (*TriggerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *TriggerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerConfig.Unmarshal(m, b)
}
func (m *TriggerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerConfig.Marshal(b, m, deterministic)
}
func (m *TriggerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerConfig.Merge(m, src)
}
func (m *TriggerConfig) XXX_Size() int {
	return xxx_messageInfo_TriggerConfig.Size(m)
}
func (m *TriggerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerConfig proto.InternalMessageInfo

func (m *TriggerConfig) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TriggerConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriggerConfig) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ConnectConfig struct {
	Initiator            *InitiatorConfig  `protobuf:"bytes,1,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Trigger              *TriggerConfig    `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Private              map[string][]byte `protobuf:"bytes,3,rep,name=private,proto3" json:"private,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConnectConfig) Reset()         { *m = ConnectConfig{} }
func (m *ConnectConfig) String() string { return proto.CompactTextString(m) }
func (*ConnectConfig) ProtoMessage()    {}
func (*ConnectConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *ConnectConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectConfig.Unmarshal(m, b)
}
func (m *ConnectConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectConfig.Marshal(b, m, deterministic)
}
func (m *ConnectConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectConfig.Merge(m, src)
}
func (m *ConnectConfig) XXX_Size() int {
	return xxx_messageInfo_ConnectConfig.Size(m)
}
func (m *ConnectConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectConfig proto.InternalMessageInfo

func (m *ConnectConfig) GetInitiator() *InitiatorConfig {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *ConnectConfig) GetTrigger() *TriggerConfig {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *ConnectConfig) GetPrivate() map[string][]byte {
	if m != nil {
		return m.Private
	}
	return nil
}

type RoamingConfig struct {
	Connects             map[string]*ConnectConfig `protobuf:"bytes,1,rep,name=connects,proto3" json:"connects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RoamingConfig) Reset()         { *m = RoamingConfig{} }
func (m *RoamingConfig) String() string { return proto.CompactTextString(m) }
func (*RoamingConfig) ProtoMessage()    {}
func (*RoamingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *RoamingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoamingConfig.Unmarshal(m, b)
}
func (m *RoamingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoamingConfig.Marshal(b, m, deterministic)
}
func (m *RoamingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoamingConfig.Merge(m, src)
}
func (m *RoamingConfig) XXX_Size() int {
	return xxx_messageInfo_RoamingConfig.Size(m)
}
func (m *RoamingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RoamingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RoamingConfig proto.InternalMessageInfo

func (m *RoamingConfig) GetConnects() map[string]*ConnectConfig {
	if m != nil {
		return m.Connects
	}
	return nil
}

func init() {
	proto.RegisterType((*InitiatorConfig)(nil), "main.InitiatorConfig")
	proto.RegisterType((*TriggerConfig)(nil), "main.TriggerConfig")
	proto.RegisterType((*ConnectConfig)(nil), "main.ConnectConfig")
	proto.RegisterMapType((map[string][]byte)(nil), "main.ConnectConfig.PrivateEntry")
	proto.RegisterType((*RoamingConfig)(nil), "main.RoamingConfig")
	proto.RegisterMapType((map[string]*ConnectConfig)(nil), "main.RoamingConfig.ConnectsEntry")
}

func init() {
	proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd)
}

var fileDescriptor_871986018790d2fd = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0xa6, 0xb4, 0xf4, 0xd2, 0x08, 0x64, 0xfe, 0x28, 0xea, 0x14, 0x32, 0x95, 0x81,
	0x0c, 0xe9, 0x82, 0x22, 0x31, 0x55, 0x0c, 0x4c, 0x14, 0x8b, 0x17, 0x30, 0xad, 0x89, 0xac, 0x12,
	0xbb, 0x72, 0x4c, 0xa5, 0xbe, 0x0d, 0xef, 0xc7, 0x4b, 0xa0, 0xf8, 0x92, 0x90, 0x20, 0xb1, 0x75,
	0x3b, 0x5f, 0xbe, 0xbb, 0xfb, 0x7d, 0x9f, 0x02, 0xb0, 0xe1, 0x96, 0x27, 0x3b, 0xa3, 0xad, 0xa6,
	0xc3, 0x82, 0x4b, 0x15, 0xbf, 0xc0, 0xd9, 0x93, 0x92, 0x56, 0x72, 0xab, 0xcd, 0x52, 0xab, 0x77,
	0x99, 0x53, 0x0a, 0xc3, 0xad, 0x54, 0x9b, 0x90, 0x44, 0x64, 0x3e, 0x61, 0xae, 0xae, 0x7a, 0x8a,
	0x17, 0x22, 0x1c, 0x60, 0xaf, 0xaa, 0xe9, 0x35, 0x8c, 0x2c, 0x37, 0xb9, 0xb0, 0xa1, 0xe7, 0xba,
	0xf5, 0x2b, 0x7e, 0x86, 0xe0, 0xd5, 0xc8, 0x3c, 0x17, 0xc7, 0x5a, 0xf8, 0x4d, 0x20, 0x58, 0x6a,
	0xa5, 0xc4, 0xda, 0xd6, 0x1b, 0x17, 0x30, 0x91, 0x0d, 0xb5, 0x5b, 0xeb, 0xa7, 0x57, 0x49, 0xe5,
	0x27, 0xf9, 0x63, 0x86, 0xfd, 0xea, 0xe8, 0x1d, 0x8c, 0x2d, 0x72, 0xb9, 0xab, 0x7e, 0x7a, 0x81,
	0x23, 0x3d, 0x58, 0xd6, 0x68, 0x68, 0x06, 0xe3, 0x9d, 0x91, 0x7b, 0x6e, 0x45, 0xe8, 0x45, 0xde,
	0xdc, 0x4f, 0x23, 0x94, 0xf7, 0x48, 0x92, 0x15, 0x4a, 0x1e, 0x95, 0x35, 0x07, 0xd6, 0x0c, 0xcc,
	0x32, 0x98, 0x76, 0x3f, 0xd0, 0x73, 0xf0, 0xb6, 0xe2, 0x50, 0x07, 0x50, 0x95, 0xf4, 0x12, 0x4e,
	0xf6, 0xfc, 0xe3, 0x13, 0x03, 0x98, 0x32, 0x7c, 0x64, 0x83, 0x7b, 0x12, 0x7f, 0x11, 0x08, 0x98,
	0xe6, 0x85, 0x54, 0x79, 0xed, 0xf6, 0x01, 0x4e, 0xd7, 0x78, 0xb4, 0x0c, 0x89, 0x43, 0xb9, 0x41,
	0x94, 0x9e, 0xac, 0x01, 0x2b, 0x91, 0xa5, 0x1d, 0x99, 0xad, 0xda, 0xf4, 0xca, 0xff, 0x68, 0x6e,
	0xbb, 0x34, 0x6d, 0x30, 0x3d, 0xa7, 0x1d, 0xc4, 0xb7, 0x91, 0xfb, 0x83, 0x16, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0xc9, 0x55, 0xbd, 0x4f, 0x02, 0x00, 0x00,
}
